---
abstract: 'Manage callbacks and control the flow of events by AnyEvent'
author:
  - 'Denis Ibaev <dionys@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Delay-Simple
no_index:
  directory:
    - t
    - inc
    - t
requires:
  AnyEvent: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: http://github.com/AdCampRu/anyevent-delay-simple/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/AdCampRu/anyevent-delay-simple
version: 0.04
